name: Upload Episode from YouTube To Spotify

on:
  push:
    paths:
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install yt-dlp
          sudo apt-get update
          sudo apt-get install -y wget curl unzip chromium-browser
          npm install

      - name: Debug GitHub Secret
        run: |
          if [ -z "${{ secrets.YOUTUBE_COOKIES }}" ]; then
            echo "❌ GitHub Secret YOUTUBE_COOKIES is empty or missing!"
            exit 1
          else
            echo "✅ GitHub Secret YOUTUBE_COOKIES exists!"
            echo "==== First 50 characters of YOUTUBE_COOKIES ===="
            echo "${{ secrets.YOUTUBE_COOKIES }}" | cut -c 1-50
          fi

      - name: Create cookies.txt from GitHub Secrets
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" | tr -d '\r' > cookies.txt
          echo "✅ Created cookies.txt successfully!"

      - name: Download YouTube Video (Full Video)
        run: |
          yt-dlp -f bestvideo+bestaudio --merge-output-format mp4 \
          --cookies cookies.txt \
          -o "episode.mp4" "$(jq -r '.id' episode.json)"

      - name: Install Puppeteer and Chrome
        run: |
          npm install puppeteer
          npx puppeteer browsers install chrome
          echo "✅ Puppeteer and Chrome installed!"

      - name: Run the YouTube to Spotify Script
        run: npm start
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          EPISODE_PATH: /github/workspace
          YOUTUBE_COOKIES_PATH: "/github/workspace/cookies.txt"
