name: 'Upload Episode from YouTube To Spotify'

on:
  push:
    paths:
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install yt-dlp

      - name: Create cookies.txt file from secret
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Download YouTube Video (Full Video)
        run: |
          yt-dlp -f bestvideo+bestaudio --merge-output-format mp4 \
          --cookies cookies.txt \
          -o "episode.mp4" "$(jq -r '.id' episode.json)"

      - name: Upload Video Episode to Spotify
        uses: Schroedinger-Hat/youtube-to-spotify@v2.5.0
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          EPISODE_PATH: /github/workspace/episode.mp4
          LOAD_THUMBNAIL: true
          URL_IN_DESCRIPTION: true
