name: Upload Episode from YouTube To Spotify

on:
  push:
    paths:
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install yt-dlp
        run: pip install yt-dlp

      # ✅ שימוש ב-cookies.txt שכבר הועלה ל-Secrets
      - name: Load cookies.txt from Secrets
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" | base64 --decode > cookies.txt
          echo "✅ Using existing cookies.txt!"

      # ✅ בדיקה אם הקובץ קיים
      - name: Verify cookies.txt exists
        run: |
          if [ -f cookies.txt ]; then
            echo "✅ cookies.txt is ready for use!"
          else
            echo "❌ cookies.txt is missing!"
            exit 1
          fi

      # ✅ שימוש ב-cookies.txt להורדת הווידאו
      - name: Download YouTube Video (Full Video)
        run: |
          yt-dlp -f bestvideo+bestaudio --merge-output-format mp4 \
          --cookies cookies.txt \
          -o "episode.mp4" "$(jq -r '.id' episode.json)"

      # ✅ העלאת הווידאו ל-Spotify **עם שימוש ב-cookies.txt**
      - name: Upload Video Episode to Spotify (Using Cookies)
        uses: Schroedinger-Hat/youtube-to-spotify@v2.5.0
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          EPISODE_PATH: /github/workspace
          YOUTUBE_COOKIES_PATH: "/github/workspace/cookies.txt"
