name: Upload Episode from YouTube To Spotify

on:
  push:
    paths:
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install yt-dlp
        run: pip install yt-dlp

      # ✅ בדיקה אם הסוד YOUTUBE_COOKIES קיים
      - name: Debug GitHub Secret
        run: |
          if [ -z "${{ secrets.YOUTUBE_COOKIES }}" ]; then
            echo "❌ GitHub Secret YOUTUBE_COOKIES is empty or missing!"
            exit 1
          else
            echo "✅ GitHub Secret YOUTUBE_COOKIES exists!"
          fi

      # ✅ יצירת קובץ cookies.txt מתוך GitHub Secrets
      - name: Create cookies.txt from GitHub Secrets
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" | tr -d '\r' > cookies.txt
          echo "✅ Created cookies.txt successfully!"

      # ✅ בדיקה אם הקובץ נוצר ונראה תקין
      - name: Verify cookies.txt format
        run: |
          echo "===== Checking cookies.txt file ====="
          if grep -q 'youtube.com' cookies.txt; then
            echo "✅ cookies.txt contains YouTube cookies."
          else
            echo "❌ cookies.txt does not contain valid YouTube cookies!"
            exit 1
          fi

      # ✅ הורדת הסרטון מ-YouTube
      - name: Download YouTube Video (Full Video)
        run: |
          echo "===== Starting video download ====="
          yt-dlp -v -f bestvideo+bestaudio --merge-output-format mp4 \
          --cookies cookies.txt \
          -o "episode.mp4" "$(jq -r '.id' episode.json)" || { echo "❌ yt-dlp failed!"; exit 1; }
          echo "✅ Video download completed!"

      # ✅ בדיקה לאיזו ספרייה אנחנו נמצאים
      - name: Check current directory
        run: |
          echo "===== Checking current working directory ====="
          pwd
          ls -lh

      # ✅ בדיקה אם הספרייה /github/workspace קיימת
      - name: Check if workspace directory exists
        run: |
          echo "===== Checking /github/workspace directory ====="
          if [ -d "/github/workspace" ]; then
            echo "✅ /github/workspace exists!"
            ls -lh /github/workspace
          else
            echo "❌ /github/workspace is missing!"
            exit 1
          fi

      # ✅ בדיקה אם הסרטון ירד בהצלחה
      - name: Check if episode.mp4 exists
        run: |
          echo "===== Checking downloaded video file ====="
          if [ -f "episode.mp4" ]; then
            echo "✅ episode.mp4 exists in current directory!"
          elif [ -f "/github/workspace/episode.mp4" ]; then
            echo "✅ episode.mp4 found in /github/workspace!"
          else
            echo "❌ episode.mp4 is missing!"
            exit 1
          fi

      # ✅ הדפסת מידע על הסרטון
      - name: Debug yt-dlp output
        run: |
          echo "===== Debugging yt-dlp output ====="
          yt-dlp --version
          yt-dlp --help
          echo "===== Checking available formats for video ====="
          yt-dlp -F "$(jq -r '.id' episode.json)"

      # ✅ העלאת הווידאו ל-Spotify **תוך שימוש ב-cookies.txt**
      - name: Upload Video Episode to Spotify (Using Cookies)
        uses: Schroedinger-Hat/youtube-to-spotify@v2.5.0
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          EPISODE_PATH: /github/workspace
          YOUTUBE_COOKIES_PATH: "/github/workspace/cookies.txt"

      # ✅ הדפסת מידע נוסף אם יש שגיאות בהעלאה ל-Spotify
      - name: Debug Cookies and Video Info
        run: |
          echo "==== Debugging cookies.txt before upload ===="
          ls -lh /github/workspace/cookies.txt
          cat /github/workspace/cookies.txt | head -n 20
          echo "==== Checking if the video file exists ===="
          ls -lh /github/workspace/episode.mp4
