name: Upload Episode from YouTube To Spotify

on:
  push:
    paths:
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install yt-dlp
        run: pip install yt-dlp

      # ✅ בדיקה אם הסוד YOUTUBE_COOKIES קיים
      - name: Debug GitHub Secret
        run: |
          if [ -z "${{ secrets.YOUTUBE_COOKIES }}" ]; then
            echo "❌ GitHub Secret YOUTUBE_COOKIES is empty or missing!"
            exit 1
          else
            echo "✅ GitHub Secret YOUTUBE_COOKIES exists!"
            echo "==== First 50 characters of YOUTUBE_COOKIES ===="
            echo "${{ secrets.YOUTUBE_COOKIES }}" | cut -c 1-50
          fi

      # ✅ יצירת קובץ cookies.txt מתוך GitHub Secrets
      - name: Create cookies.txt from GitHub Secrets
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" | tr -d '\r' > cookies.txt
          echo "✅ Created cookies.txt successfully!"

      # ✅ בדיקה אם הקובץ נוצר כהלכה + הצגת השורות הראשונות
      - name: Debug cookies file
        run: |
          echo "===== Debugging cookies.txt ====="
          if [ -f cookies.txt ]; then
            echo "✅ cookies.txt exists!"
          else
            echo "❌ cookies.txt is missing!"
            exit 1
          fi
          echo "===== Showing first 20 lines of cookies.txt ====="
          head -n 20 cookies.txt
          echo "===== Showing special characters ====="
          od -c cookies.txt

      # ✅ הורדת הסרטון מ-YouTube בעזרת yt-dlp + שימוש ב-cookies.txt
      - name: Download YouTube Video (Full Video)
        run: |
          yt-dlp -f bestvideo+bestaudio --merge-output-format mp4 \
          --cookies cookies.txt \
          -o "episode.mp4" "$(jq -r '.id' episode.json)"

      # ✅ העלאת הווידאו ל-Spotify **תוך שימוש ב-cookies.txt**
      - name: Upload Video Episode to Spotify (Using Cookies)
        uses: amram3133/youtube_to_spotify@main  # השתמש בריפוזיטורי שלך
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          EPISODE_PATH: /github/workspace
          YOUTUBE_COOKIES_PATH: "/github/workspace/cookies.txt"

      # ✅ דיבוג אחרי העלאה
      - name: Debug After Upload
        run: |
          echo "==== Debugging after Spotify upload ===="
          ls -lh /github/workspace/
