name: Upload Episode from YouTube To Spotify

on:
  push:
    paths:
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set working directory
        run: |
          echo "===== Checking current working directory ====="
          pwd
          echo "===== Listing files in current directory ====="
          ls -lh
          echo "===== Changing working directory to repository location ====="
          cd /home/runner/work/youtube-to-spotify/youtube-to-spotify || exit 1
          echo "===== New working directory ====="
          pwd
          echo "WORKSPACE_PATH=/home/runner/work/youtube-to-spotify/youtube-to-spotify" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install yt-dlp
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # ✅ בדיקה אם הסוד YOUTUBE_COOKIES קיים
      - name: Debug GitHub Secret
        run: |
          if [ -z "${{ secrets.YOUTUBE_COOKIES }}" ]; then
            echo "❌ GitHub Secret YOUTUBE_COOKIES is empty or missing!"
            exit 1
          else
            echo "✅ GitHub Secret YOUTUBE_COOKIES exists!"
            echo "==== First 50 characters of YOUTUBE_COOKIES ===="
            echo "${{ secrets.YOUTUBE_COOKIES }}" | cut -c 1-50
          fi

      # ✅ יצירת קובץ cookies.txt מתוך GitHub Secrets
      - name: Create cookies.txt from GitHub Secrets
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" | tr -d '\r' > cookies.txt
          echo "✅ Created cookies.txt successfully!"

      # ✅ בדיקה אם הקובץ נוצר כהלכה + הצגת השורות הראשונות
      - name: Debug cookies file
        run: |
          echo "===== Debugging cookies.txt ====="
          if [ -f cookies.txt ]; then
            echo "✅ cookies.txt exists!"
          else
            echo "❌ cookies.txt is missing!"
            exit 1
          fi
          echo "===== Showing first 20 lines of cookies.txt ====="
          head -n 20 cookies.txt
          echo "===== Showing special characters ====="
          od -c cookies.txt

      # ✅ הורדת הסרטון מ-YouTube בעזרת yt-dlp + שימוש ב-cookies.txt
      - name: Download YouTube Video (Full Video)
        run: |
          yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]" \
          --merge-output-format mp4 \
          --cookies cookies.txt \
          -o "episode.mp4" "$(jq -r '.id' episode.json)"

      # ✅ אם הקובץ לא נוצר, ננסה למזג את קובצי ה-webm ל-mp4
      - name: Convert WebM to MP4 if needed
        run: |
          if [ ! -f episode.mp4 ]; then
            echo "❌ episode.mp4 is missing, trying to merge WebM files..."
            if [ -f episode.f313.webm ] && [ -f episode.f251.webm ]; then
              ffmpeg -i episode.f313.webm -i episode.f251.webm \
              -c:v copy -c:a aac episode.mp4
            fi
          fi

      # ✅ בדיקה אם הקובץ episode.mp4 קיים
      - name: Check Downloaded Video
        run: |
          echo "===== Checking downloaded video file ====="
          if [ ! -f episode.mp4 ]; then
            echo "❌ episode.mp4 is missing!"
            echo "===== Listing all files in workspace ====="
            ls -lh
            exit 1
          else
            echo "✅ episode.mp4 exists!"
          fi

      # ✅ הצגת קבצים בתיקייה כדי לוודא שהקובץ במקום הנכון
      - name: Debug Files Before Upload
        run: |
          echo "===== Listing all files before upload ====="
          ls -lh /home/runner/work/youtube-to-spotify/youtube-to-spotify
          ls -lh /github/workspace || echo "❌ /github/workspace is missing"

      # ✅ העלאת הווידאו ל-Spotify **תוך שימוש ב-cookies.txt**
      - name: Upload Video Episode to Spotify (Using Cookies)
        uses: amram3133/youtube_to_spotify@main
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          EPISODE_PATH: /home/runner/work/youtube-to-spotify/youtube-to-spotify/episode.mp4
          YOUTUBE_COOKIES_PATH: "/home/runner/work/youtube-to-spotify/youtube-to-spotify/cookies.txt"

      # ✅ בדיקת סטטוס סופי
      - name: Debug Final Status
        run: |
          echo "===== Final check ====="
          echo "Spotify upload process completed, check logs above for errors."
